import { ProductsByCategory } from "@/types/product";

export const productsList: ProductsByCategory[] = [
  {
    category: "Бэстселлер",
    products: [
      {
        image: "https://picsum.photos/id/63/200/300",
        slug: "uzem-7",
        name: "Үзэм-7",
        englishName: "Uzem-7",
        type: "үрэл",
        tags: ["зүрх", "ходоод"],
        description: "нэг юманд уунаа",
        price: 5000,
      },
      {
        image: "https://picsum.photos/id/63/200/300",
        slug: "uzem-7",
        name: "Үзэм-7",
        englishName: "Uzem-7",
        type: "үрэл",
        tags: ["зүрх", "ходоод"],
        description: "нэг юманд уунаа",
        price: 5000,
      },
      {
        image: "https://picsum.photos/id/63/200/300",
        slug: "uzem-7",
        name: "Үзэм-7",
        englishName: "Uzem-7",
        type: "үрэл",
        tags: ["зүрх", "ходоод"],
        description: "нэг юманд уунаа",
        price: 5000,
      },
      {
        image: "https://picsum.photos/id/63/200/300",
        slug: "uzem-7",
        name: "Үзэм-7",
        englishName: "Uzem-7",
        type: "үрэл",
        tags: ["зүрх", "ходоод"],
        description: "нэг юманд уунаа",
        price: 5000,
      },
      {
        image: "https://picsum.photos/id/63/200/300",
        slug: "uzem-7",
        name: "Үзэм-7",
        englishName: "Uzem-7",
        type: "үрэл",
        tags: ["зүрх", "ходоод"],
        description: "нэг юманд уунаа",
        price: 5000,
      },
      {
        image: "https://picsum.photos/id/63/200/300",
        slug: "uzem-7",
        name: "Үзэм-7",
        englishName: "Uzem-7",
        type: "үрэл",
        tags: ["зүрх", "ходоод"],
        description: "нэг юманд уунаа",
        price: 5000,
      },
      {
        image: "https://picsum.photos/id/63/200/300",
        slug: "uzem-7",
        name: "Үзэм-7",
        englishName: "Uzem-7",
        type: "үрэл",
        tags: ["зүрх", "ходоод"],
        description: "нэг юманд уунаа",
        price: 5000,
      },
      {
        image: "https://picsum.photos/id/63/200/300",
        slug: "uzem-7",
        name: "Үзэм-7",
        englishName: "Uzem-7",
        type: "үрэл",
        tags: ["зүрх", "ходоод"],
        description: "нэг юманд уунаа",
        price: 5000,
      },
    ],
  },
];
