import type { Metadata } from "next";
import { rubik, gip } from "@/lib/fonts";
import "./globals.css";
import { Navigation } from "@/components/Navigation";
import { ThemeProvider } from "@/provider/ThemeProvider";
import { Footer } from "@/components/Footer";
import { BuiltByTseku } from "@/components/BuiltBy";

export const metadata: Metadata = {
  title: "Baigal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="mn"
      className={`${gip.variable} ${rubik.variable} antialiased`}
      suppressHydrationWarning
    >
      <body className="px-2">
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <Navigation />
          <div className="my-10">{children}</div>
          <Footer />
          <BuiltByTseku />
        </ThemeProvider>
      </body>
    </html>
  );
}
